version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1

workflows:
  build-and-deploy:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: auto_sizing
          filters:
            branches:
              only:
                main