version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1

jobs:
  build:
    docker:
    - image: python:3.11
    steps:
    - checkout
    - restore_cache:
        keys:
          # when lock files change, use increasingly general patterns to restore cache
          - &cache_key
            python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-{{ checksum "requirements.txt" }}
          - python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-
          - python-packages-v1-{{ .Branch }}-
          - python-packages-v1-
    - &build
      run:
        name: Build
        command: |
          python3.11 -m venv venv/
          venv/bin/pip install --progress-bar off --upgrade -r requirements.txt
    - run:
        name: PyTest
        command: venv/bin/pytest --black --ignore=auto_sizing/tests/integration/
    - run:
        name: flake8
        command: venv/bin/flake8 auto_sizing
    - run:
        name: isort
        command: venv/bin/isort --check auto_sizing
    - run:
        name: Mypy
        command: venv/bin/mypy auto_sizing
    - save_cache:
        paths:
        - venv/
        key: *cache_key
  build_docker:
    docker:
    - image: cimg/base:2024.07
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build docker image
        command: |
          docker build --no-cache -t "auto-sizing-test" .

workflows:
  build-and-deploy:
    jobs:
      - build
      - build_docker:
          filters:
            branches:
              ignore:
                main
      - gcp-gcr/build-and-push-image:
          requires:
            - build
          image: auto_sizing
          filters:
            branches:
              only:
                main
