apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: auto_sizing-
spec:
  entrypoint: auto_sizing
  arguments:
    parameters:
    - name: targets  # set dynamically when workflow gets deployed
    - name: project_id
    - name: dataset_id
    - name: bucket
  templates:
  - name: auto_sizing
    parallelism: 5  # run up to 5 containers in parallel at the same time
    inputs:
      parameters:
        - name: targets
    steps:
    - - name: ensure-enrollments-and-analyze
        template: ensure-enrollments-and-analyze
        arguments:
          parameters:
          - name: slug
            value: "{{item.slug}}"
          - name: dates
            value: "{{item.dates}}"
        withParam: "{{inputs.parameters.targets}}"  # process these targets in parallel
        continueOn:
          failed: true

  - name: auto-sizing
    inputs:
      parameters:
      - name: date
      - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/auto_sizing:latest
      command: [
        auto_sizing, --log_to_bigquery, run,
        "--target_slug={{inputs.parameters.slug}}",
        "--dataset_id={{workflow.parameters.dataset_id}}",
        "--project_id={{workflow.parameters.project_id}}",
        "--bucket={{workflow.parameters.bucket}}",
        "--run_presets"
      ]
      resources:
        requests:
          memory: 10Gi   # make sure there is at least 10Gb of memory available for the task
        limits:
          cpu: 4  # limit to 4 cores
    retryStrategy:
      limit: 3  # execute a container max. 3x; sometimes a container run might fail due to limited resources
      retryPolicy: "Always"
      backoff:
        duration: "1m"
        factor: 2
        maxDuration: "5m"

  - name: export-statistics
    inputs:
      parameters:
        - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/auto_sizing:latest
      command: [
        auto_sizing, export-statistics-to-json,
        "--dataset_id={{workflow.parameters.dataset_id}}",
        "--project_id={{workflow.parameters.project_id}}",
        "--target_slug={{inputs.parameters.slug}}",
        "--bucket={{workflow.parameters.bucket}}"
      ]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes

  - name: analyse-and-export
    inputs:
      parameters:
        - name: slug
        - name: date
    steps:
    - - name: auto-sizing
        template: auto-sizing  
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
    - - name: export-statistics
        template: export-statistics
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
